{% set version = "0.1.0" %}
{% set name = "array-record" %}

# This is the recipe for array-record
package:
   name: {{ name }}
   version: {{ version }}

source:
  git_url: https://github.com/google/array_record
  git_rev: v{{ version }}

build:
  number: 1
  noarch: python
  string: pyh{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
  script: python -m pip install .

requirements:
  host:
     - python
  run:
   # conda build requirements
     - python
     - zipp
     - importlib_resources {{ importlib_resources }}
     - typing_extensions {{ typing_extensions }}
     - absl-py {{ absl_py }}
     - etils

about:
  home: https://github.com/google/array_record
  license: Apache License 2.0
  license_family: APACHE
  license_file: ../LICENSE
  summary: "A new file format derived from Riegeli"
  description: |
      ArrayRecord is a new file format derived from Riegeli,
      achieving a new frontier of IO efficiency. 
  dev_url: https://github.com/google/array_record
  doc_url: https://github.com/google/array_record

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
